name: build-pdfs

on:
  push:
    branches: [ cmu-2013-fall ]
  pull_request:
    branches: [ cmu-2013-fall ]
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install texlive texlive-latex-extra lmodern latexmk
    - name: Run make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: pdfs
        path: "**/*.pdf"
